version = 0.1

[default.deploy.parameters]
stack_name = "mchack"
resolve_s3 = true
s3_prefix = "mchack"
region = "ap-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
