AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Dev:
  ```
  export SS=mchack SN=graphql-backend; yes | sam deploy --resolve-s3 --s3-prefix=$SS --stack-name $SS-$SN -t ./template.yml --parameter-overrides StackName=$SN StackSet=$SS `cat development.properties` WorkaroundSubSSM=$(date --iso-8601=s)
  ```
Outputs:
  UserTableName:
    Description: "The name of the DynamoDB UserTable"
    Value: !Ref 'UserIdTable'
Parameters:
  ENV:
    Type: String
  EventIdTableUserGsiName:
    Type: String
  StackName:
    Type: String
  StackSet:
    Type: String
  UserIdTableUsernameGsiName:
    Type: String
Resources:
  EventIdTable:
    Properties:
      AttributeDefinitions:
        - AttributeName: eventId
          AttributeType: S
        - AttributeName: ownerId
          AttributeType: S
      BillingMode: PROVISIONED
      GlobalSecondaryIndexes:
        - IndexName: !Ref 'EventIdTableUserGsiName'
          KeySchema:
            - AttributeName: ownerId
              KeyType: HASH
            - AttributeName: eventId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      KeySchema:
        - AttributeName: eventId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
    Type: AWS::DynamoDB::Table
  EventIdTableArn:
    Properties:
      Name: !Sub '/${StackSet}/${ENV}/${StackName}/dynamodb/event-id-table/arn'
      Type: String
      Value: !GetAtt 'EventIdTable.Arn'
    Type: AWS::SSM::Parameter
  EventIdTableName:
    Properties:
      Name: !Sub '/${StackSet}/${ENV}/${StackName}/dynamodb/event-id-table/table-name'
      Type: String
      Value: !Ref 'EventIdTable'
    Type: AWS::SSM::Parameter
  GraphQL:
    Properties:
      CodeUri: ./js-graphql
      Environment:
        Variables:
          EVENT_ID_TABLE_NAME: !Ref 'EventIdTable'
          EVENT_ID_TABLE_USER_GSI_NAME: !Ref 'EventIdTableUserGsiName'
          USER_ID_TABLE_NAME: !Ref 'UserIdTable'
          USER_ID_TABLE_USERNAME_GSI_NAME: !Ref 'UserIdTableUsernameGsiName'
      Events:
        HttpGet:
          Properties:
            Method: GET
            Path: /graphql
          Type: Api
        HttpOptions:
          Properties:
            Method: OPTIONS
            Path: /graphql
          Type: Api
        HttpPost:
          Properties:
            Method: POST
            Path: /graphql
          Type: Api
        HttpPut:
          Properties:
            Method: PUT
            Path: /graphql
          Type: Api
      Handler: src/index.handler
      Policies:
        - Statement:
            - Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Query
                - dynamodb:*
              Effect: Allow
              Resource:
                - !GetAtt 'UserIdTable.Arn'
                - !Sub "${UserIdTable.Arn}/index/*"
                - !GetAtt 'EventIdTable.Arn'
                - !Sub "${EventIdTable.Arn}/index/*"
                - arn:aws:dynamodb:*:*:table/*
          Version: "2012-10-17"
      Runtime: nodejs22.x
      Timeout: 30
    Type: AWS::Serverless::Function
  UserIdTable:
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "username"
          AttributeType: "S"
      BillingMode: PROVISIONED
      GlobalSecondaryIndexes:
        - IndexName: !Ref 'UserIdTableUsernameGsiName'
          KeySchema:
            - AttributeName: "username"
              KeyType: "HASH"
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
    Type: AWS::DynamoDB::Table
  UserIdTableArn:
    Properties:
      Name: !Sub '/${StackSet}/${ENV}/${StackName}/dynamodb/user-id-table/arn'
      Type: String
      Value: !GetAtt 'UserIdTable.Arn'
    Type: AWS::SSM::Parameter
  UserIdTableName:
    Properties:
      Name: !Sub '/${StackSet}/${ENV}/${StackName}/dynamodb/user-id-table/table-name'
      Type: String
      Value: !Ref 'UserIdTable'
    Type: AWS::SSM::Parameter
Transform: AWS::Serverless-2016-10-31
