AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Local Dev, run under this directory:
  ```
  pushd ..; export SS=mchack SN=graphql-backend; bash resolve-ssm.sh; popd
  export SS=mchack SN=graphql-backend; sam local start-api -t ./local-api.yml --parameter-overrides StackName=$SN StackSet=$SS `cat ../development.properties ../parameters.properties` WorkaroundSubSSM=$(date --iso-8601=s) --host 0.0.0.0 -l lambda.log
  ```
Parameters:
  ENV:
    Type: String
  StackName:
    Type: String
  StackSet:
    Type: String
  UserIdTableName:
    Type: String
  UserIdTableUsernameGsiName:
    Type: String
Resources:
  GraphQL:
    Properties:
      CodeUri: ./
      Environment:
        Variables:
          USER_ID_TABLE_NAME: !Ref 'UserIdTableName'
          USER_ID_TABLE_USERNAME_GSI_NAME: !Ref 'UserIdTableUsernameGsiName'
      Events:
        HttpGet:
          Properties:
            Method: GET
            Path: /graphql
          Type: Api
        HttpPost:
          Properties:
            Method: POST
            Path: /graphql
          Type: Api
        HttpPut:
          Properties:
            Method: PUT
            Path: /graphql
          Type: Api
      Handler: src/index.handler
      Runtime: nodejs22.x
      Timeout: 30
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
